### ISSUE TITLE
run with multiple sample

### ISSUE THREAD

**Issue by HuairenZhang** [Wedge-lab/dpclust#22]
I was trying with the inst/example/run_nd.sh but came across the following error:

Error in if (is.na(indices)) { : the condition has length > 1
Calls: RunDP ... DirichletProcessClustering -> Gibbs.subclone.density.est
Execution halted

Could you please help? Thank you.

**Comment by Avramis** [comment]
Thank you for pointing it out. We'll investigate the issue and offer guidance on running the script

**Comment by Avramis** [comment]
This issue is due to differences in the implementation of the is.na function across R versions. In older versions (v3.2 and earlier), is.na returned a single TRUE or FALSE if a vector contained an "NA" value. In newer versions, however, it returns a vector of TRUE/FALSE values, which is causing the issue you’re experiencing. We've implemented a fix that should work across all current versions of R.

**Comment by Coaxecva** [comment]
Hi, I was wondering if this issue has been resolved. I encountered the same error when running `./run_nd.sh` after installing DPClust from GitHub:

> [1] "1800  /  2000"
> [1] "1900  /  2000"
> [1] "2000  /  2000"
> [1] "Estimating density between pairs of samples..."
> [1] "Samples 1 and 2"
> Error in if (is.na(indices)) { : the condition has length > 1
> Calls: RunDP ... DirichletProcessClustering -> Gibbs.subclone.density.est
> Execution halted

Any guidance would be appreciated!

**Comment by Avramis** [comment]
Hi,
You can use the hotfix_if_is_na branch (https://github.com/Wedge-lab/dpclust3p/tree/hotfix_if_is_na) to resolve the is.na error encountered in later versions of R.

**Comment by Coaxecva** [comment]
Thanks for pointing out the branch — just to confirm, it’s from dpclust3p, right?

I reinstalled the package using:
`devtools::install_github("Wedge-lab/dpclust3p", ref = "hotfix_if_is_na")`

Then I ran `./run_nd.sh`, but I'm still getting the same error:

```
[1] "1900  /  2000"
[1] "2000  /  2000"
[1] "Estimating density between pairs of samples..."
[1] "Samples 1 and 2"
Error in if (is.na(indices)) { : the condition has length > 1
Calls: RunDP ... DirichletProcessClustering -> Gibbs.subclone.density.est
Execution halted
```
